### ISSUE TITLE
Take indentation into account when parsing

### ISSUE THREAD

**Issue by justinvdm** [praekelt/numl#20]
At the moment, we don't take indentation account, which means this:

``` yaml
foo:
  bar: baz
quux: corge
```

is parsed as this:

``` js
{
  foo: {
    bar: 'baz',
    quux: 'corge'
  }
}
```
